import type { BlockDefinition } from "./types";

export const BLOCK_DEFINITIONS: BlockDefinition[] = [
  {
    type: "hero",
    label: "قسم البطل",
    icon: "LayoutTemplate",
    category: "layout",
    defaultProps: {
      title: "منصة المنتجات الرقمية الأولى",
      subtitle: "اكتشف مجموعة واسعة من المنتجات الرقمية عالية الجودة",
      backgroundColor: "#6366f1",
      backgroundImage: "",
      ctaText: "ابدأ الآن",
      ctaUrl: "#",
      overlayOpacity: 40,
      textColor: "#ffffff",
    },
    defaultSize: { width: 900, height: 420 },
  },
  {
    type: "features",
    label: "شبكة المميزات",
    icon: "LayoutGrid",
    category: "layout",
    defaultProps: {
      title: "لماذا تختارنا؟",
      columns: 3,
      features: [
        { icon: "Zap", title: "سرعة فائقة", description: "تحميل فوري للمنتجات الرقمية بعد الشراء" },
        { icon: "Shield", title: "أمان متقدم", description: "حماية عالية لملفاتك وبياناتك" },
        { icon: "Headphones", title: "دعم متواصل", description: "فريق دعم متاح على مدار الساعة" },
      ],
    },
    defaultSize: { width: 900, height: 380 },
  },
  {
    type: "columns",
    label: "أعمدة",
    icon: "Columns3",
    category: "layout",
    defaultProps: {
      columnCount: 2,
      gap: 24,
      columnWidths: [50, 50],
    },
    defaultSize: { width: 900, height: 300 },
  },
  {
    type: "divider",
    label: "فاصل",
    icon: "Minus",
    category: "layout",
    defaultProps: {
      style: "solid",
      color: "#e5e7eb",
      thickness: 1,
      width: 100,
    },
    defaultSize: { width: 900, height: 20 },
  },
  {
    type: "spacer",
    label: "مسافة فارغة",
    icon: "ArrowUpDown",
    category: "layout",
    defaultProps: {
      height: 60,
    },
    defaultSize: { width: 900, height: 60 },
  },
  {
    type: "heading",
    label: "عنوان",
    icon: "Type",
    category: "content",
    defaultProps: {
      text: "عنوان جديد",
      level: "h2",
      alignment: "center",
      color: "#111827",
      fontSize: 32,
    },
    defaultSize: { width: 900, height: 60 },
  },
  {
    type: "text",
    label: "نص",
    icon: "AlignLeft",
    category: "content",
    defaultProps: {
      text: "أضف نصك هنا. يمكنك كتابة محتوى تسويقي يجذب العملاء ويزيد من التحويلات.",
      alignment: "center",
      fontSize: 16,
      color: "#6b7280",
    },
    defaultSize: { width: 900, height: 80 },
  },
  {
    type: "button",
    label: "زر",
    icon: "MousePointerClick",
    category: "content",
    defaultProps: {
      label: "اضغط هنا",
      url: "#",
      variant: "primary",
      size: "md",
      alignment: "center",
    },
    defaultSize: { width: 200, height: 50 },
  },
  {
    type: "image",
    label: "صورة",
    icon: "Image",
    category: "content",
    defaultProps: {
      url: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=500&fit=crop",
      alt: "صورة وصفية",
      objectFit: "cover",
      borderRadius: 8,
    },
    defaultSize: { width: 900, height: 400 },
  },
  {
    type: "faq",
    label: "الأسئلة الشائعة",
    icon: "HelpCircle",
    category: "content",
    defaultProps: {
      title: "الأسئلة الشائعة",
      items: [
        { question: "كيف أستلم المنتج الرقمي؟", answer: "يتم إرسال رابط التحميل فوراً إلى بريدك الإلكتروني بعد إتمام عملية الشراء." },
        { question: "هل يمكنني استرجاع المبلغ؟", answer: "نعم، يمكنك طلب استرجاع المبلغ خلال 30 يوماً من تاريخ الشراء." },
        { question: "هل المنتجات قابلة للتحديث؟", answer: "نعم، جميع المنتجات تتلقى تحديثات دورية مجاناً." },
      ],
      style: "accordion",
    },
    defaultSize: { width: 900, height: 400 },
  },
  {
    type: "pricing",
    label: "جدول التسعير",
    icon: "CreditCard",
    category: "commerce",
    defaultProps: {
      title: "خطط الأسعار",
      plans: [
        { name: "الأساسي", price: "49", period: "شهرياً", features: ["5 منتجات", "1 جيجاباخص 저장", "دعم بريد إلكتروني"], highlighted: false, cta: "اشترك الآن" },
        { name: "الاحترافي", price: "99", period: "شهرياً", features: ["منتجات غير محدودة", "50 جيجاباخص تخزين", "دعم أولوية", "تحليلات متقدمة"], highlighted: true, cta: "الأشهر الشائعة" },
        { name: "المؤسسات", price: "199", period: "شهرياً", features: ["كل مميزات الاحترافي", "API مخصص", "مدير حساب مخصص", "SLA مخصص"], highlighted: false, cta: "تواصل معنا" },
      ],
    },
    defaultSize: { width: 900, height: 450 },
  },
  {
    type: "countdown",
    label: "عد تنازلي",
    icon: "Timer",
    category: "commerce",
    defaultProps: {
      endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      label: "العرض ينتهي خلال",
      backgroundColor: "#1e1b4b",
      textColor: "#ffffff",
    },
    defaultSize: { width: 900, height: 120 },
  },
  {
    type: "social-proof",
    label: "الدليل الاجتماعي",
    icon: "Users",
    category: "social",
    defaultProps: {
      counterValue: 12500,
      label: "عميل سعيد",
      avatars: [
        "https://i.pravatar.cc/40?img=1",
        "https://i.pravatar.cc/40?img=2",
        "https://i.pravatar.cc/40?img=3",
        "https://i.pravatar.cc/40?img=4",
        "https://i.pravatar.cc/40?img=5",
      ],
    },
    defaultSize: { width: 400, height: 80 },
  },
  {
    type: "cta",
    label: "دعوة للإجراء",
    icon: "Megaphone",
    category: "commerce",
    defaultProps: {
      title: "جاهز للبدء؟",
      subtitle: "انضم لآلاف العملاء الراضين وابدأ رحلتك الرقمية اليوم",
      buttonText: "ابدأ مجاناً",
      buttonUrl: "#",
      backgroundColor: "#6366f1",
      textColor: "#ffffff",
    },
    defaultSize: { width: 900, height: 280 },
  },
  {
    type: "testimonials",
    label: "شهادات العملاء",
    icon: "Quote",
    category: "social",
    defaultProps: {
      title: "ماذا يقول عملاؤنا",
      items: [
        { name: "أحمد الشمري", role: "مصمم جرافيك", quote: "منصة رائعة ساعدتني في بيع تصاميمني بسهولة. الدعم الفني ممتاز والمنصة سهلة الاستخدام.", avatar: "https://i.pravatar.cc/80?img=11" },
        { name: "سارة العتيبي", role: "مطورة ويب", quote: "أفضل منصة لبيع المنتجات الرقمية. التحليلات تساعدني على فهم سلوك العملاء وتحسين مبيعاتي.", avatar: "https://i.pravatar.cc/80?img=5" },
        { name: "خالد المطيري", role: "صانع محتوى", quote: "أنصح الجميع باستخدام هذه المنصة. سهولة الاستخدام والمميزات المتعددة جعلت تجربتي مميزة.", avatar: "https://i.pravatar.cc/80?img=8" },
      ],
    },
    defaultSize: { width: 900, height: 350 },
  },
  {
    type: "video",
    label: "فيديو",
    icon: "Play",
    category: "media",
    defaultProps: {
      url: "",
      autoplay: false,
      muted: true,
      aspectRatio: "16/9",
    },
    defaultSize: { width: 900, height: 506 },
  },
];

export const BLOCK_CATEGORIES = [
  { id: "layout", label: "التخطيط" },
  { id: "content", label: "المحتوى" },
  { id: "commerce", label: "التجارة" },
  { id: "media", label: "الوسائط" },
  { id: "social", label: "الاجتماعي" },
] as const;
